/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as BazaarRouteImport } from './routes/bazaar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPricesRouteImport } from './routes/admin/prices'

const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const BazaarRoute = BazaarRouteImport.update({
  id: '/bazaar',
  path: '/bazaar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricesRoute = AdminPricesRouteImport.update({
  id: '/admin/prices',
  path: '/admin/prices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bazaar': typeof BazaarRoute
  '/items': typeof ItemsRoute
  '/admin/prices': typeof AdminPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bazaar': typeof BazaarRoute
  '/items': typeof ItemsRoute
  '/admin/prices': typeof AdminPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bazaar': typeof BazaarRoute
  '/items': typeof ItemsRoute
  '/admin/prices': typeof AdminPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bazaar' | '/items' | '/admin/prices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bazaar' | '/items' | '/admin/prices'
  id: '__root__' | '/' | '/bazaar' | '/items' | '/admin/prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BazaarRoute: typeof BazaarRoute
  ItemsRoute: typeof ItemsRoute
  AdminPricesRoute: typeof AdminPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazaar': {
      id: '/bazaar'
      path: '/bazaar'
      fullPath: '/bazaar'
      preLoaderRoute: typeof BazaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prices': {
      id: '/admin/prices'
      path: '/admin/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AdminPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BazaarRoute: BazaarRoute,
  ItemsRoute: ItemsRoute,
  AdminPricesRoute: AdminPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
